services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    Model\Mapper\MonologMapper:
        factory: Component\MapperFactory:create
        arguments:
            - 'Model\Mapper\MonologMapper'
