# home
root:
    path: /
    defaults:
        resource: "landing"
    methods: [GET, POST]
    
monolog:
    path: /{resource}{slash}{action}
    requirements:
        resource: "monolog"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]